### REGISTRATION
POST http://localhost:3000/v1/api/register
Content-Type: application/json

{
  "name": "Jordach Makaya",
  "email": "jordach@content.co",
  "password":"PassWord@201"
}


### LOGIN
POST http://localhost:3000/v1/api/login
Content-Type: application/json

{
  "email": "jordach@content.co",
  "password":"PassWord@201"
}
